<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="POL-6MXJDB3" failures="1" tests="3" name="testngTest" time="0.124" errors="0" timestamp="2024-02-11T09:05:23 CET">
  <testcase classname="com.dydko.basic.reporterlog.EmailReport" name="skipTest" time="0.005">
    <skipped/>
  </testcase> <!-- skipTest -->
  <testcase classname="com.dydko.basic.reporterlog.EmailReport" name="failTest" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.dydko.basic.reporterlog.EmailReport.failTest(EmailReport.java:39)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- failTest -->
  <testcase classname="com.dydko.basic.reporterlog.EmailReport" name="passTest" time="0.083"/>
</testsuite> <!-- testngTest -->
